name: CI

on:
  push:
    branches:
      - main
      - "dependabot/**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    uses: stylelint/.github/.github/workflows/lint.yml@reusable-workflow # TODO: Change to `@main`

  test:
    uses: stylelint/.github/.github/workflows/test.yml@reusable-workflow # TODO: Change to `@main`
    with:
      node-version: '["12", "14", "16", "18"]'
