name: CI

on:
  push:
    branches:
      - main
      - "dependabot/**"
  pull_request:
    branches:
      - "**"

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install latest npm
        run: npm install --global npm@latest

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

  test:
    uses: stylelint/.github/.github/workflows/test.yml@reusable-workflow # TODO: Change to `@main`
    with:
      node-version: '["12", "14", "16", "18"]'
